name: LOCAL_LINK CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      changed_services: ${{steps.changed.outputs.services}}
      frontend_changed: ${{steps.changed.outputs.frontend}}
    steps:
     - uses: actions/checkout@v3
     - name: Detect changed services
       id: changed
       run: |
        SERVICES="ApiGateway AvailabilityService BookingService PaymentsService ReviewService UserService ServiceListingService"
        CHANGED_SERVICES=""
        for SERVICE in $SERVICES; do
          if git diff --name-only HEAD~1 HEAD --$SERVICE; then
            echo "$SERVICE unchanged"
          else
            echo "$SERVICE changed"
            CHANGED_SERVICES="$CHANGED_SERVICES $SERVICE"
        fi
        done
        FRONTEND_CHANGED="false"
                 if ! git diff --quiet HEAD~1 HEAD -- frontend; then
                   FRONTEND_CHANGED="true"
                 fi

                 echo "services=$CHANGED_SERVICES" >> $GITHUB_OUTPUT
                 echo "frontend=$FRONTEND_CHANGED" >> $GITHUB_OUTPUT

  build:
    needs: detect_changes
    runs-on: ubuntu-latest
    if: needs.detect_changes.outputs.changed_services != '' || needs.detect_changes.outputs.frontend_changed == 'true'
    steps:
        - uses: actions/checkout@v3
        - name: Set up JDK 21
          uses: actions/setup-java@v3
          with:
            distribution: 'temurin'
            java-version: '21'
        - name: Build changed spring boot services
          if: ${{ needs.detect_changes.outputs.changed_services != '' }}
          run: |
            for SERVICE in ${{ needs.detect_changes.outputs.changed_services }}; do
              echo "Building $SERVICE"
              mvn -f $SERVICE/pom.xml clean install -DskipTests
            done
      # ---------- Frontend -----------
        - name: Set up Node
          if: needs.detect_changes.outputs.frontend_changed == 'true'
          uses: actions/setup-node@v3
          with:
            node-version: 18

        - name: Build Vite Frontend
          if: needs.detect_changes.outputs.frontend_changed == 'true'
          run: |
            cd frontend
            npm install
            npm run build

      # ---------- Docker Login -----------
        - name: Docker login
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

      # ---------- Build & Push Docker Images -----------
        - name: Build & Push Microservice Images
          if: ${{ needs.detect_changes.outputs.changed_services != '' }}
          run: |
            for SERVICE in ${{ needs.detect_changes.outputs.changed_services }}; do
              IMAGE="${{ secrets.DOCKER_USERNAME }}/$SERVICE:latest"
              echo "Dockerizing $SERVICE â†’ $IMAGE"
              docker build -t "$IMAGE" "$SERVICE"
              docker push "$IMAGE"
            done

        - name: Build & Push Frontend Image
          if: needs.detect_changes.outputs.frontend_changed == 'true'
          run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest frontend
            docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest